(cl:in-package #:common-lisp-user)

(defpackage #:khazern
  (:use #:common-lisp)
  (:shadow
   #:condition)
  (:export #:*accumulation-var*
           #:*epilogue-tag*
           #:*index*
           #:*it-var*
           #:*loop-name*
           #:*placeholder-result*
           #:*start*
           #:accumulation-clause
           #:add-binding
           #:add-destructuring-binding
           #:add-simple-binding
           #:afterword-forms
           #:analyze
           #:being-cars
           #:being-cons
           #:being-hash-entries
           #:being-hash-keys
           #:being-hash-values
           #:being-lists
           #:being-package-symbols
           #:being-region
           #:being-vector-elements
           #:binding-clause
           #:body-forms
           #:body-region
           #:category
           #:check-nullable-simple-var-spec
           #:check-subtype
           #:clause
           #:clause-group
           #:d-type-spec 
           #:d-var-spec 
           #:declarations
           #:define-interface
           #:dynamic-extent-p
           #:end
           #:epilogue-forms
           #:expand-assignments
           #:expand-body
           #:features-list
           #:for-as-region
           #:form
           #:ignorablep
           #:list-scope
           #:make-scope
           #:map-variables
           #:maybe-parse-token
           #:nullable-simple-var
           #:other-var
           #:parallel-superclause
           #:parse-accumulation
           #:parse-clause
           #:parse-compound-forms
           #:parse-conjunctive-clauses
           #:parse-d-spec
           #:parse-into
           #:parse-preposition
           #:parse-prepositions
           #:parse-token
           #:parse-type-spec
           #:parse-using
           #:parse-var-spec
           #:preposition-names
           #:prologue-forms
           #:scope-functions
           #:scope-reference
           #:scope-references
           #:selectable-region
           #:sequence-scope
           #:simple-var
           #:standard-client
           #:start
           #:step-intro-forms
           #:step-outro-forms
           #:subclauses
           #:symbol-equal
           #:type-spec
           #:unparse-token
           #:var
           #:var-spec
           #:variable-list
           #:with-gensyms
           #:with-region
           #:wrap-forms))
