name: test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.lisp }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        lisp:
        - abcl
        - ccl
        - clasp
        - ecl
        - sbcl
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yitzchak/archlinux-cl:latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
    - name: Setup Lisp Environment
      run: |
        make-rc
        asdf-add
    - name: Run ANSI and Regression Tests
      run: |
        lisp -i ${{ matrix.lisp }} -e "(ql:quickload :khazern-extrinsic/test)" -e "(asdf:test-system :khazern-extrinsic)"
    - name: Run Extension Tests
      run: |
        lisp -i ${{ matrix.lisp }} -e "(ql:quickload :khazern-extension-extrinsic/test)" -e "(asdf:test-system :khazern-extension-extrinsic)"
